name: CI

on:
  push:
    branches: [main]
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@d7793b545071e98d581d3bf084a51c3213318a07 # v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      - name: Run Lint
        run: ./gradlew detekt spotlessCheck

  test:
    name: Test
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        java-version: [17, 21]
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@d7793b545071e98d581d3bf084a51c3213318a07 # v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: "temurin"
          cache: "gradle"

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3

      - name: Run Tests
        uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3
        with:
          arguments: test koverXmlReport --continue --scan

      - name: Upload Coverage
        if: matrix.java-version == '17'
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
        with:
          files: altertable/build/reports/kover/report.xml
          fail_ci_if_error: false

  integration:
    name: Integration Tests
    runs-on: ubuntu-24.04
    services:
      altertable:
        image: ghcr.io/altertable-ai/altertable-mock:latest
        ports:
          - 15001:15001
        env:
          ALTERTABLE_MOCK_API_KEYS: "valid_api_key"
          ALTERTABLE_MOCK_ENVIRONMENTS: "production,integration_env"
        options: >-
          --health-cmd "exit 0"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 3
          --health-start-period 10s

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@d7793b545071e98d581d3bf084a51c3213318a07 # v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      - name: Run Integration Tests
        run: ./gradlew integrationTest --continue

  check:
    name: Check
    runs-on: ubuntu-24.04
    needs: [lint, test, integration]
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@d7793b545071e98d581d3bf084a51c3213318a07 # v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      - name: ABI and Coverage
        run: ./gradlew checkLegacyAbi koverVerify --continue
